# Generated by Django 6.0.1 on 2026-02-25 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('requested_role', models.CharField(choices=[('user', 'User'), ('supervisor', 'Supervisor'), ('cio', 'CIO')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Supervisor', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '帳號申請',
                'verbose_name_plural': '帳號申請列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('a_name', models.CharField(max_length=50, verbose_name='申請人')),
                ('department', models.CharField(max_length=50, verbose_name='部門')),
                ('a_purpose', models.TextField(verbose_name='申請目的')),
                ('a_type', models.CharField(max_length=50, verbose_name='申請類型')),
                ('service_system', models.CharField(blank=True, max_length=100, verbose_name='服務系統')),
                ('status', models.CharField(choices=[('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Supervisor', max_length=30)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='applications/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '服務申請',
                'verbose_name_plural': '服務申請列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='發布人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('supervisor', 'Supervisor'), ('cio', 'CIO'), ('admin', 'Admin')], default='user', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
