# Generated by Django 6.0.2 on 2026-03-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_pw',
            field=models.BooleanField(default=True, verbose_name='Must change password'),
        ),
    ]
