# Generated by Django 6.0.2 on 2026-03-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_userprofile_must_change_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('cio', 'CIO'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
