# Generated by Django 6.0.2 on 2026-03-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bookmark',
            field=models.TextField(blank=True, default='', verbose_name='Bookmark (審核備註)'),
        ),
        migrations.AddField(
            model_name='application',
            name='preview_by',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Under-preview 設定者角色'),
        ),
        migrations.AlterField(
            model_name='application',
            name='a_type',
            field=models.CharField(choices=[('API access', 'API Access'), ('System access', 'System Access'), ('Data access', 'Data Access'), ('Other', 'Other (System Function / Process Change)')], max_length=50, verbose_name='申請類型'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Under-preview', 'Under-preview'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Work-in-progress', 'Work-in-progress'), ('Request Completed', 'Request Completed'), ('Rejected', 'Rejected')], default='Pending Supervisor', max_length=30),
        ),
    ]
