# Generated by Django 6.0.2 on 2026-03-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_application_bookmark_application_preview_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('cio', 'CIO')], default='user', max_length=20),
        ),
    ]
