# Generated by Django 6.0.2 on 2026-04-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_return_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Supervisor', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Under-preview', 'Under-preview'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Work-in-progress', 'Work-in-progress'), ('Request Completed', 'Request Completed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Supervisor', max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return'), ('resubmit', 'Resubmit'), ('preview', 'Under-Preview'), ('resume', 'Resume'), ('complete', 'Complete'), ('bookmark', 'Bookmark')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(blank=True, default='', max_length=30)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='portal.application')),
            ],
            options={
                'verbose_name': '審核歷程',
                'verbose_name_plural': '審核歷程列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
