# Generated by Django 6.0.2 on 2026-04-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_accountrequest_status_alter_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_tl_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='requested_role',
            field=models.CharField(choices=[('user', 'User'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('cio', 'CIO')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('Pending Team_Leader', 'Pending Team Leader'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Under-preview', 'Under-preview'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Work-in-progress', 'Work-in-progress'), ('Request Completed', 'Request Completed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=30),
        ),
    ]
