# Generated by Django 6.0.2 on 2026-05-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_accountrequest_team_leader_application_team_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('Pending Team Leader', 'Pending Team Leader'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Under-preview', 'Under-preview'), ('Pending Team Leader', 'Pending Team Leader'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Work-in-progress', 'Work-in-progress'), ('Request Completed', 'Request Completed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=30),
        ),
    ]
