# Generated by Django 6.0.2 on 2026-05-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_accountrequest_status_alter_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('purpose', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hardware/')),
                ('preview_by', models.CharField(blank=True, max_length=50)),
                ('return_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending Team Leader', 'Pending Team Leader'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending Hardware Supervisor', 'Pending Hardware Supervisor'), ('Under-preview', 'Under-preview'), ('Work-in-progress', 'Work-in-progress'), ('Request Completed', 'Request Completed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hardware_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_hs', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_sp', to=settings.AUTH_USER_MODEL)),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_tl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
