# Generated by Django 6.0.2 on 2026-05-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_hardwarerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('team_leader', 'Team Leader'), ('supervisor', 'Supervisor'), ('hardware_supervisor', 'Hardware Supervisor'), ('cio', 'CIO')], default='user', max_length=20),
        ),
    ]
