# Generated by Django 6.0.2 on 2026-05-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_userprofile_role'),
    ]

    operations = [
    ]
