# Generated by Django 6.0.2 on 2026-05-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_merge_20260505_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退件日期'),
        ),
        migrations.AddField(
            model_name='application',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退件日期'),
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退件日期'),
        ),
    ]
