# Generated by Django 6.0.2 on 2026-05-14 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_accountrequest_return_date_application_return_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hardwarerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HardwareApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return'), ('resubmit', 'Resubmit'), ('preview', 'Under-Preview'), ('resume', 'Resume'), ('complete', 'Complete')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(blank=True, default='', max_length=50)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hardware_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='portal.hardwarerequest')),
            ],
            options={
                'verbose_name': '硬體申請審核歷程',
                'verbose_name_plural': '硬體申請審核歷程列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
