# Generated by Django 6.0.2 on 2026-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_hardwarerequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='preview_by',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Under-preview 設定者角色'),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='status',
            field=models.CharField(choices=[('Pending Team Leader', 'Pending Team Leader'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Under-preview', 'Under-preview'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=30),
        ),
    ]
