# Generated by Django 6.0.2 on 2026-07-01 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_byodrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('software_name', models.CharField(max_length=150)),
                ('software_version', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('request_type', models.CharField(choices=[('New Installation', 'New Installation'), ('Version Upgrade', 'Version Upgrade'), ('License Renewal', 'License Renewal'), ('Trial Software', 'Trial Software'), ('Open Source Tool', 'Open Source Tool'), ('Other', 'Other')], default='New Installation', max_length=50)),
                ('license_type', models.CharField(choices=[('Freeware', 'Freeware'), ('Open Source', 'Open Source'), ('Commercial', 'Commercial'), ('Subscription', 'Subscription'), ('Trial', 'Trial'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('target_device', models.CharField(blank=True, max_length=150, verbose_name='Target Device / Asset')),
                ('business_purpose', models.TextField()),
                ('data_level', models.CharField(choices=[('Public', 'Public'), ('Internal', 'Internal'), ('Confidential', 'Confidential'), ('Personal Data', 'Personal Data'), ('Sensitive', 'Sensitive')], default='Internal', max_length=50)),
                ('internet_access_required', models.BooleanField(default=False)),
                ('admin_privilege_required', models.BooleanField(default=False)),
                ('security_concern', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='software_requests/')),
                ('status', models.CharField(choices=[('Pending Team Leader', 'Pending Team Leader'), ('Pending Supervisor', 'Pending Supervisor'), ('Pending CIO', 'Pending CIO'), ('Under-preview', 'Under-preview'), ('Work-in-progress', 'Work-in-progress'), ('Request Completed', 'Request Completed'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending Team Leader', max_length=50)),
                ('preview_by', models.CharField(blank=True, default='', max_length=50)),
                ('return_reason', models.TextField(blank=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('bookmark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '軟體申請',
                'verbose_name_plural': '軟體申請列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('return', 'Return'), ('resubmit', 'Resubmit'), ('preview', 'Under-Preview'), ('resume', 'Resume'), ('complete', 'Complete'), ('bookmark', 'Bookmark')], max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=50)),
                ('to_status', models.CharField(blank=True, default='', max_length=50)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('software_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='portal.softwarerequest')),
            ],
            options={
                'verbose_name': '軟體申請審核歷程',
                'verbose_name_plural': '軟體申請審核歷程列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
