# Generated by Django 6.0.2 on 2026-08-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_softwarerequest_softwareapprovalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hardware_supervisor',
            field=models.BooleanField(default=False, help_text='Allows this user to approve and complete hardware requests at the Hardware Supervisor stage.', verbose_name='Hardware Supervisor Permission'),
        ),
    ]
